spring.application.name=careernavigator

spring.datasource.url=jdbc:mysql://localhost:3306/careernavigator
spring.datasource.username=root
spring.datasource.password=Sriram@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true